src_lib += files(
  'i15_add.c',
  'i15_bitlen.c',
  'i15_decmod.c',
  'i15_decode.c',
  'i15_decred.c',
  'i15_encode.c',
  'i15_fmont.c',
  'i15_iszero.c',
  'i15_moddiv.c',
  'i15_modpow2.c',
  'i15_modpow.c',
  'i15_montmul.c',
  'i15_mulacc.c',
  'i15_muladd.c',
  'i15_ninv15.c',
  'i15_reduce.c',
  'i15_rshift.c',
  'i15_sub.c',
  'i15_tmont.c',
  'i31_add.c',
  'i31_bitlen.c',
  'i31_decmod.c',
  'i31_decode.c',
  'i31_decred.c',
  'i31_encode.c',
  'i31_fmont.c',
  'i31_iszero.c',
  'i31_moddiv.c',
  'i31_modpow2.c',
  'i31_modpow.c',
  'i31_montmul.c',
  'i31_mulacc.c',
  'i31_muladd.c',
  'i31_ninv31.c',
  'i31_reduce.c',
  'i31_rshift.c',
  'i31_sub.c',
  'i31_tmont.c',
  'i32_add.c',
  'i32_bitlen.c',
  'i32_decmod.c',
  'i32_decode.c',
  'i32_decred.c',
  'i32_div32.c',
  'i32_encode.c',
  'i32_fmont.c',
  'i32_iszero.c',
  'i32_modpow.c',
  'i32_montmul.c',
  'i32_mulacc.c',
  'i32_muladd.c',
  'i32_ninv32.c',
  'i32_reduce.c',
  'i32_sub.c',
  'i32_tmont.c',
  'i62_modpow2.c',
)
