version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ci
    groups:
      actions:
        patterns: ["*"]
    labels: []
    schedule:
      interval: monthly
