option(
    'override',
    type: 'boolean',
    value: true,
    description: 'Override the standard malloc interface (i.e. define entry points for malloc, free, etc)',
)
option(
    'win_redirect',
    type: 'boolean',
    value: false,
    description: 'Use redirection module (mimalloc-redirect) on Windows if compiling mimalloc as a DLL',
)
option(
    'tl_model',
    type: 'combo',
    choices: ['DEFAULT', 'PTHREADS', 'FIXED', 'LOCAL', 'LOCAL_DYNAMIC', 'WIN32'],
    description: 'Force TLS model: PTHREADS (pthread locals), FIXED (fixed thread local slots), LOCAL (thread local variables), LOCAL_DYNAMIC (dlopen-compatible thread local storage mechanism (Unix)), WIN32 (direct Windows TLS slots)',
)
