src_lib += files(
  'prf.c',
  'prf_md5sha1.c',
  'prf_sha256.c',
  'prf_sha384.c',
  'ssl_ccert_single_ec.c',
  'ssl_ccert_single_rsa.c',
  'ssl_client.c',
  'ssl_client_default_rsapub.c',
  'ssl_client_full.c',
  'ssl_engine.c',
  'ssl_engine_default_aescbc.c',
  'ssl_engine_default_aesccm.c',
  'ssl_engine_default_aesgcm.c',
  'ssl_engine_default_chapol.c',
  'ssl_engine_default_descbc.c',
  'ssl_engine_default_ec.c',
  'ssl_engine_default_ecdsa.c',
  'ssl_engine_default_rsavrfy.c',
  'ssl_hashes.c',
  'ssl_hs_client.c',
  'ssl_hs_server.c',
  'ssl_io.c',
  'ssl_keyexport.c',
  'ssl_lru.c',
  'ssl_rec_cbc.c',
  'ssl_rec_ccm.c',
  'ssl_rec_chapol.c',
  'ssl_rec_gcm.c',
  'ssl_scert_single_ec.c',
  'ssl_scert_single_rsa.c',
  'ssl_server.c',
  'ssl_server_full_ec.c',
  'ssl_server_full_rsa.c',
  'ssl_server_mine2c.c',
  'ssl_server_mine2g.c',
  'ssl_server_minf2c.c',
  'ssl_server_minf2g.c',
  'ssl_server_minr2g.c',
  'ssl_server_minu2g.c',
  'ssl_server_minv2g.c',
)
