diff --git a/deps/openssl/config/Makefile b/deps/openssl/config/Makefile
index 48d2af80..8913d9c5 100644
--- a/deps/openssl/config/Makefile
+++ b/deps/openssl/config/Makefile
@@ -1,23 +1,33 @@
-# This Makefile is confirmed to be run only on Linux (CentOS and
-# Ubuntu). perl5 and gas(>=2.26) are needed.
+# This Makefile is confirmed to be run on Linux (CentOS and
+# Ubuntu), macOS, or on a MSYS2 shell.
+# perl5, nasm, and either gas(>=2.26) or LLVM(>= 9.0) are needed.
 
-UNAME_S := $(shell uname -s)
-ifneq ($(UNAME_S),Linux)
-  $(error This can be run only on Linux)
+UNAME_S := $(shell uname -o)
+ifneq (, $(findstring Linux,$(UNAME_S)))
+	UNAME_OK:=true
+endif
+ifeq ($(UNAME_S),Msys)
+	UNAME_OK:=true
+endif
+ifeq ($(UNAME_S),Darwin)
+	UNAME_OK:=true
+endif
+ifneq ($(UNAME_OK),true)
+  $(error This can be run only on Linux, MSYS or macOS)
 endif
 
 PERL    = perl
 
 # Supported architecture list
-ASM_ARCHS = aix64-gcc-as BSD-x86 BSD-x86_64 \
+ASM_ARCHS = BSD-x86 BSD-x86_64 \
 darwin64-x86_64-cc darwin-i386-cc darwin64-arm64-cc linux-aarch64 \
-linux-armv4 linux-elf linux-x86_64 \
-linux-ppc64le linux32-s390x linux64-s390x linux64-mips64\
-solaris-x86-gcc solaris64-x86_64-gcc VC-WIN64A VC-WIN32
+linux-armv4 linux-elf linux-x32 linux-x86_64 linux-ppc \
+linux-ppc64le linux64-s390x linux64-mips64\
+solaris-x86-gcc solaris64-x86_64-gcc VC-WIN64A VC-WIN32 mingw mingw64
 
 NO_ASM_ARCHS = VC-WIN64-ARM linux64-riscv64 linux64-loongarch64
 
-CC = gcc
+CC ?= gcc
 FAKE_GCC = ../config/fake_gcc.pl
 
 CONFIGURE = ./Configure
@@ -53,10 +63,6 @@ all: $(ASM_ARCHS) $(NO_ASM_ARCHS) generate_headers
 $(ASM_ARCHS):
 	cd $(OPSSL_SRC); $(NO_WARN_ENV) CC=$(CC) $(PERL) $(CONFIGURE) $(COPTS) $@;
 	$(PERL) -w -I$(OPSSL_SRC) $(GENERATE) asm $@ "${GEN_HEADERS}" "${CRYPTO_GEN_HEADERS}"
-# Confgure asm_avx2 and generate upto avx2 support
-	cd $(OPSSL_SRC); $(NO_WARN_ENV) CC=$(FAKE_GCC) $(PERL) $(CONFIGURE) \
-	$(COPTS) $@;
-	$(PERL) -w -I$(OPSSL_SRC) $(GENERATE) asm_avx2 $@ "${GEN_HEADERS}" "${CRYTO_GEN_HEADERS}"
 # Configure no-asm and generate no-asm sources
 	cd $(OPSSL_SRC); $(NO_WARN_ENV) $(PERL) $(CONFIGURE) $(COPTS) \
 	no-asm $@;
