src_lib += files(
  'rsa_default_keygen.c',
  'rsa_default_modulus.c',
  'rsa_default_oaep_decrypt.c',
  'rsa_default_oaep_encrypt.c',
  'rsa_default_pkcs1_sign.c',
  'rsa_default_pkcs1_vrfy.c',
  'rsa_default_priv.c',
  'rsa_default_privexp.c',
  'rsa_default_pub.c',
  'rsa_default_pubexp.c',
  'rsa_i15_keygen.c',
  'rsa_i15_modulus.c',
  'rsa_i15_oaep_decrypt.c',
  'rsa_i15_oaep_encrypt.c',
  'rsa_i15_pkcs1_sign.c',
  'rsa_i15_pkcs1_vrfy.c',
  'rsa_i15_priv.c',
  'rsa_i15_privexp.c',
  'rsa_i15_pub.c',
  'rsa_i15_pubexp.c',
  'rsa_i31_keygen.c',
  'rsa_i31_keygen_inner.c',
  'rsa_i31_modulus.c',
  'rsa_i31_oaep_decrypt.c',
  'rsa_i31_oaep_encrypt.c',
  'rsa_i31_pkcs1_sign.c',
  'rsa_i31_pkcs1_vrfy.c',
  'rsa_i31_priv.c',
  'rsa_i31_privexp.c',
  'rsa_i31_pub.c',
  'rsa_i31_pubexp.c',
  'rsa_i32_oaep_decrypt.c',
  'rsa_i32_oaep_encrypt.c',
  'rsa_i32_pkcs1_sign.c',
  'rsa_i32_pkcs1_vrfy.c',
  'rsa_i32_priv.c',
  'rsa_i32_pub.c',
  'rsa_i62_keygen.c',
  'rsa_i62_oaep_decrypt.c',
  'rsa_i62_oaep_encrypt.c',
  'rsa_i62_pkcs1_sign.c',
  'rsa_i62_pkcs1_vrfy.c',
  'rsa_i62_priv.c',
  'rsa_i62_pub.c',
  'rsa_oaep_pad.c',
  'rsa_oaep_unpad.c',
  'rsa_pkcs1_sig_pad.c',
  'rsa_pkcs1_sig_unpad.c',
  'rsa_ssl_decrypt.c',
)
