#!/bin/bash

generate_cap_names() {
    cat <<EOF > "$1"
/* Generated by libcap build system */
const char *cap_names[] = {
    "cap_chown",
    "cap_dac_override",
    "cap_dac_read_search",
    "cap_fowner",
    "cap_fsetid",
    "cap_kill",
    "cap_setgid",
    "cap_setuid",
    "cap_setpcap",
    "cap_linux_immutable",
    "cap_net_bind_service",
    "cap_net_broadcast",
    "cap_net_admin",
    "cap_net_raw",
    "cap_ipc_lock",
    "cap_ipc_owner",
    "cap_sys_module",
    "cap_sys_rawio",
    "cap_sys_chroot",
    "cap_sys_ptrace",
    "cap_sys_pacct",
    "cap_sys_admin",
    "cap_sys_boot",
    "cap_sys_nice",
    "cap_sys_resource",
    "cap_sys_time",
    "cap_sys_tty_config",
    "cap_mknod",
    "cap_lease",
    "cap_audit_write",
    "cap_audit_control",
    "cap_setfcap",
    "cap_mac_override",
    "cap_mac_admin",
    "cap_syslog",
    "cap_wake_alarm",
    "cap_block_suspend",
    "cap_audit_read",
    "cap_perfmon",
    "cap_bpf",
    "cap_checkpoint_restore",
    NULL
};
EOF
}

patch_makenames() {
    sed -e 's/#include "cap_names.list.h"//' \
       -e '/^int main(/i const char *cap_names[] = {"dummy", NULL};' \
       "$1" > "$2"
}

case "$1" in
    generate)
        generate_cap_names "$2"
        ;;
    patch)
        patch_makenames "$2" "$3"
        ;;
    *)
        echo "Uso: $0 [generate|patch]"
        exit 1
        ;;
esac
