src_lib += files(
  'ec_all_m15.c',
  'ec_all_m31.c',
  'ec_c25519_i15.c',
  'ec_c25519_i31.c',
  'ec_c25519_m15.c',
  'ec_c25519_m31.c',
  'ec_curve25519.c',
  'ec_default.c',
  'ec_keygen.c',
  'ec_p256_m15.c',
  'ec_p256_m31.c',
  'ec_prime_i15.c',
  'ec_prime_i31.c',
  'ec_pubkey.c',
  'ec_secp256r1.c',
  'ec_secp384r1.c',
  'ec_secp521r1.c',
  'ecdsa_atr.c',
  'ecdsa_default_sign_asn1.c',
  'ecdsa_default_sign_raw.c',
  'ecdsa_default_vrfy_asn1.c',
  'ecdsa_default_vrfy_raw.c',
  'ecdsa_i15_bits.c',
  'ecdsa_i15_sign_asn1.c',
  'ecdsa_i15_sign_raw.c',
  'ecdsa_i15_vrfy_asn1.c',
  'ecdsa_i15_vrfy_raw.c',
  'ecdsa_i31_bits.c',
  'ecdsa_i31_sign_asn1.c',
  'ecdsa_i31_sign_raw.c',
  'ecdsa_i31_vrfy_asn1.c',
  'ecdsa_i31_vrfy_raw.c',
  'ecdsa_rta.c',
)
