src_lib += files(
  'aes_big_cbcdec.c',
  'aes_big_cbcenc.c',
  'aes_big_ctr.c',
  'aes_big_ctrcbc.c',
  'aes_big_dec.c',
  'aes_big_enc.c',
  'aes_common.c',
  'aes_ct64.c',
  'aes_ct64_cbcdec.c',
  'aes_ct64_cbcenc.c',
  'aes_ct64_ctr.c',
  'aes_ct64_ctrcbc.c',
  'aes_ct64_dec.c',
  'aes_ct64_enc.c',
  'aes_ct.c',
  'aes_ct_cbcdec.c',
  'aes_ct_cbcenc.c',
  'aes_ct_ctr.c',
  'aes_ct_ctrcbc.c',
  'aes_ct_dec.c',
  'aes_ct_enc.c',
  'aes_pwr8.c',
  'aes_pwr8_cbcdec.c',
  'aes_pwr8_cbcenc.c',
  'aes_pwr8_ctr.c',
  'aes_pwr8_ctrcbc.c',
  'aes_small_cbcdec.c',
  'aes_small_cbcenc.c',
  'aes_small_ctr.c',
  'aes_small_ctrcbc.c',
  'aes_small_dec.c',
  'aes_small_enc.c',
  'aes_x86ni.c',
  'aes_x86ni_cbcdec.c',
  'aes_x86ni_cbcenc.c',
  'aes_x86ni_ctr.c',
  'aes_x86ni_ctrcbc.c',
  'chacha20_ct.c',
  'chacha20_sse2.c',
  'des_ct.c',
  'des_ct_cbcdec.c',
  'des_ct_cbcenc.c',
  'des_support.c',
  'des_tab.c',
  'des_tab_cbcdec.c',
  'des_tab_cbcenc.c',
  'poly1305_ctmul32.c',
  'poly1305_ctmul.c',
  'poly1305_ctmulq.c',
  'poly1305_i15.c',
)
